### PR TITLE
WIP: Feature: add pickup directory option

### PR DESCRIPTION
**Pull request by RyKilleen**
Addresses #12 

Would love input on any necessary tests to add / ways I could improve.

@nblumhardt is there a best practice method for testing a locally developed modification, or is creating a private nuget stream the only way to bring in the modified App?

### CODE REVIEW

**Comment by nblumhardt** [comment]
Thanks Ryan! Nicely done - I'm not sure about the way this fits with SMTP server configuration though. I.e. `SmtpServer` is a required setting currently - for this to work I think we'd need to make it optional, which could lead to a bit of confusion.

What are your thoughts on publishing a separate "Email Pickup" app? Pros/cons?

**Comment by RyKilleen** [comment]
I hadn't considered that, it'd certainly be a confusing interaction. If it were possible to toggle between one or the other, I think it would fit more inline with this plugin (and would avoid too much fragmentation.) 

Barring that I suppose it'd make sense to publish it separately, the con being that I'm not too experienced in this area.

**Comment by nblumhardt** [comment]
Thanks for the follow-up. Toggling somehow would be nice but I don't think this will be able to be added to Seq for a while.

Perhaps (if you're running successfully on your forked/updated version) we could leave this to see whether anyone else has the same requirement, and pick it back up at that time? It's not a huge effort to publish a new package, but also probably no rush unless it is impacting you.

**Comment by nblumhardt** [comment]
Just a quick check-in; closing this one as I don't think we have any action planned on it - let me know how things are going, if you need any help along these lines. Cheers!

**Pull request closed without merging**
