### PR TITLE
Enhanced formatting for alerts

### PR DESCRIPTION
**Pull request by nblumhardt**
If the event type is the pre-defined "alert" type, the email shows the details of the alert, results that triggered it, and a link to view these interactively.

image

### CODE REVIEW

**Comment by normanhh3** [comment]
These alerts look really interesting.  Is there a doc page on www.getseq.net that can tell me more about how to create and use them?

**Comment by nblumhardt** [comment]
Thanks for the note Norman. Documentation is on this week's list. The UI should be _reasonably_ self-explanatory; from a dashboard chart, expand the chart details and select the _Alerts_ tab. It would be really valuable to hear of any "gotchas" or points of confusion/difficulty that you encounter trying to set it up (we can use that to improve the UI and/or docs :-))

I'll post a link here when 4.0 documentation is online 👍

**Comment by normanhh3** [comment]
I think I missed if this feature is only available in the 4.0.55
pre-release?

**Comment by nblumhardt** [comment]
@normanhh3 thanks for the follow-up. Yes, it's in the latest pre-release only.

**Comment by normanhh3** [comment]
Thanks for the tweet earlier with pointers and docs. Looks like great stuff coming!

**Pull request merged**
